GREETING_MESSAGE = "\n" \
                "***  tAIkymas   ***\n" \
                "***  Main Menu  ***\n" \
                "Choose action (enter number):\n" \
                "\t1. What's the purpose of the game?\n" \
                "\t2. What's my goal as a player?\n" \
                "\t3. How does the game work (rules etc.)?\n" \
                "\t4. Start the game!\n" \
                "\t5. Exit the game.\n" \
                "\n"

GAME_PURPOSE_MESSAGE = "The purpose of the game is to engage in creative thinking and problem solving,\n" \
                       "in order to come up with profitable and effective business/product ideas. The game \n" \
                       "will provide you with certain scenarios and your mission is to think outside the box\n" \
                       "to make the most out of the situations!" \
                       ""

PLAYER_GOAL_MESSAGE = "As a player, you will present your business/startup ideas and compete with ideas generated by\n" \
                      "artificial intelligence (AI). Be prepared to stand strong for your ideas, as you will be\n" \
                      "asked to back them up with strong arguments - prove how they are profitable, good for the\n" \
                      "environment etc.\n" \
                      ""

GAME_RULES_MESSAGE = "The game consists of 2 modes:\n" \
                     "\t1. CV mode\n" \
                     "\t\tA computer will generate CVs of 3 people and present them to you. The program (AI) will\n" \
                     "\t\talso present its business idea involving these 3 people. Next, you'll be asked to enter\n" \
                     "\t\tyour own business/startup idea. Then, the program will play the role of an investor, who\n" \
                     "\t\twill evaluate the 2 ideas and give constructive thoughts. Next, both the AI and you will\n" \
                     "\t\thave a chance to respond to the investor by giving additional arguments why your idea\n" \
                     "\t\tis better. In total, up to 3 arguments can be provided (3 argument exchanges). Finally,\n" \
                     "\t\tthe program will consider all points stated by both sides and declare the winner.\n" \
                     "\t2. Organisation mode\n" \
                     "\t\tThe principle of this game mode is similar to the 1st one, except that this time you\n" \
                     "\t\twill be given descriptions of 2 companies and their work/projects. Your task is to compete\n" \
                     "\t\twith AI and think of the better business/startup idea, that the 2 companies could do together.\n" \
                     "\n"

CHOOSE_GAME_MODE_MENU_MESSAGE = "\n" \
                "Choose game mode (enter number):\n" \
                "\t1. CV mode.\n" \
                "\t2. Organisation mode.\n" \
                "\t3. Return to main menu.\n" \
                "\t4. Exit the game.\n" \
                "\n"

INVALID_OPTION_MESSAGE = '\nNo such option! Please try again.\n'
EXIT_MESSAGE = '\nGoodbye!\n'
